<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="brubank.GitHubUserValidatorInterceptorSpec" tests="5" skipped="0" failures="0" errors="0" timestamp="2018-08-19T03:40:05" hostname="ARAR017385" time="0.21">
  <properties/>
  <testcase name="github user exists in the cache" classname="brubank.GitHubUserValidatorInterceptorSpec" time="0.147"/>
  <testcase name="github user exists but is not in the cache" classname="brubank.GitHubUserValidatorInterceptorSpec" time="0.024"/>
  <testcase name="github user does not exist" classname="brubank.GitHubUserValidatorInterceptorSpec" time="0.013"/>
  <testcase name="github user has no location set" classname="brubank.GitHubUserValidatorInterceptorSpec" time="0.012"/>
  <testcase name="check for user raises exception" classname="brubank.GitHubUserValidatorInterceptorSpec" time="0.012"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
